name: Update Stock Screener Data

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    - cron: '0 8 * * *' # 每日午夜 (UTC) 執行，約為台灣時間早上8點

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data update script
        run: python update_data.py

      - name: Update Gist with new data
        env:
          GH_TOKEN: ${{ secrets.GIST_SECRET }}
        run: |
          gh gist edit ${{ secrets.GIST_ID }} preprocessed_data.json
