name: Update Stock Screener Data

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    - cron: '0 0 * * *' # 每日午夜 (UTC) 自動執行

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data update script
        run: python update_data.py

      - name: Update Gist with new data
        uses: joshuacurtis/sync-to-gist-action@v1
        with:
          file-path: 'preprocessed_data.json'
          gist-id: ${{ secrets.GIST_ID }}
          gist-token: ${{ secrets.GIST_SECRET }}
